version: '3.9'

services:
  php:
    build:
      context: ./php
    volumes:
      - ../www:/var/www/html/
    ports:
      - 8001:80
    links:
      - db
    networks:
      - default
  db:
    image: mysql
    container_name: nameDb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: myDb
      MYSQL_USER: user
      MYSQL_PASSWORD: test
    command: mysqld --sql_mode="" --character-set-server=utf8 --collation-server=utf8_slovenian_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    restart: always
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    networks:
      - default
  phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
volumes:
  persistent: